# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e64fa664255b6a06f1a8e1367777ef19c207732dd984d30d23bacb04313b56e4d6b5c35cef2e7bd13d664b8bf5671effefc6aaefa0538156427673035ad3c50

test:
  secret_key_base: 403c19d2ab550fae82cd184548dbcea5005da3b91759fe882b90032913987eb273d47885b0938725e2eb8132887c3c31cc8891bae5e1ca322df36ad08a6c66dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
